// Single source for Vivid Velocity tokens. DESIGN.md is the authoritative spec;
// keep keys + values aligned. tokens.test.ts asserts the alignment programmatically.

export const colors = {
  surface: '#131315',
  surfaceDim: '#131315',
  surfaceBright: '#39393b',
  surfaceContainerLowest: '#0e0e10',
  surfaceContainerLow: '#1b1b1d',
  surfaceContainer: '#201f21',
  surfaceContainerHigh: '#2a2a2c',
  surfaceContainerHighest: '#353437',
  onSurface: '#e5e1e4',
  onSurfaceVariant: '#d0c2d5',
  inverseSurface: '#e5e1e4',
  inverseOnSurface: '#303032',
  outline: '#998d9e',
  outlineVariant: '#4d4353',
  surfaceTint: '#e0b6ff',
  primary: '#e0b6ff',
  onPrimary: '#4c007d',
  primaryContainer: '#9d4edd',
  onPrimaryContainer: '#fffdff',
  inversePrimary: '#8433c4',
  secondary: '#41ee8d',
  onSecondary: '#00391b',
  secondaryContainer: '#00d174',
  onSecondaryContainer: '#00532b',
  tertiary: '#edc156',
  onTertiary: '#3f2e00',
  tertiaryContainer: '#947000',
  onTertiaryContainer: '#fffdff',
  error: '#ffb4ab',
  onError: '#690005',
  errorContainer: '#93000a',
  onErrorContainer: '#ffdad6',
  primaryFixed: '#f2daff',
  primaryFixedDim: '#e0b6ff',
  onPrimaryFixed: '#2e004e',
  onPrimaryFixedVariant: '#6a0baa',
  secondaryFixed: '#5dff9e',
  secondaryFixedDim: '#2fe283',
  onSecondaryFixed: '#00210e',
  onSecondaryFixedVariant: '#00522a',
  tertiaryFixed: '#ffdf9a',
  tertiaryFixedDim: '#edc156',
  onTertiaryFixed: '#251a00',
  onTertiaryFixedVariant: '#5a4300',
  background: '#131315',
  onBackground: '#e5e1e4',
  surfaceVariant: '#353437',
} as const;

export const typography = {
  displayLg: {
    fontFamily: 'Hanken Grotesk',
    fontSize: 48,
    fontWeight: 800,
    lineHeight: 56,
    letterSpacing: '-0.02em',
  },
  headlineLg: {
    fontFamily: 'Hanken Grotesk',
    fontSize: 32,
    fontWeight: 700,
    lineHeight: 40,
    letterSpacing: '-0.01em',
  },
  headlineLgMobile: {
    fontFamily: 'Hanken Grotesk',
    fontSize: 28,
    fontWeight: 700,
    lineHeight: 36,
  },
  titleMd: {
    fontFamily: 'Hanken Grotesk',
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 28,
  },
  bodyLg: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: 400,
    lineHeight: 24,
  },
  bodySm: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 20,
  },
  labelCaps: {
    fontFamily: 'JetBrains Mono',
    fontSize: 12,
    fontWeight: 600,
    lineHeight: 16,
    letterSpacing: '0.05em',
    textTransform: 'uppercase' as const,
  },
  codeSm: {
    fontFamily: 'JetBrains Mono',
    fontSize: 13,
    fontWeight: 400,
    lineHeight: 18,
  },
} as const;

export const radii = {
  sm: 4,
  default: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 9999,
} as const;

export const spacing = {
  base: 8,
  xs: 4,
  sm: 12,
  md: 24,
  lg: 48,
  xl: 80,
  gutter: 20,
  marginMobile: 16,
  marginDesktop: 32,
} as const;

export const motion = {
  micro: 120,
  standard: 180,
  emphatic: 280,
  easeStandard: 'cubic-bezier(0.4, 0, 0.2, 1)',
  easeEmphatic: 'cubic-bezier(0.16, 1, 0.3, 1)',
} as const;
